### ISSUE TITLE
This is a rat and ratting is a crime! 

### ISSUE THREAD

**Issue by EvilBytecode** [baris1337/growdice-fake-mines-predictor#2]
https://tria.ge/240113-vqrjqacgdr/behavioral2
[Analysis.pdf](https://github.com/baris1337/growdice-fake-mines-predictor/files/13928963/Analysis.pdf)
![Exposed](https://github.com/baris1337/growdice-fake-mines-predictor/assets/151552809/3471daf8-d691-4513-a44d-d73630d50b03)

**Comment by baris1337** [comment]
its open sourced lil man wym 😂😂

**Comment by EvilBytecode** [comment]
https://github.com/baris1337/growdice-fake-mines-predictor/blob/main/start.bat

Yeah Obfuscated.

**Comment by EvilBytecode** [comment]
Link 2 check if y want : https://tria.ge/240113-vqrjqacgdr/behavioral2
PDF Sample Analysis Static : https://github.com/baris1337/growdice-fake-mines-predictor/files/13928963/Analysis.pdf
Exposed : https://github.com/baris1337/growdice-fake-mines-predictor/assets/151552809/3471daf8-d691-4513-a44d-d73630d50b03
What is seroxen? : https://media.discordapp.net/attachments/1193623153319088311/1195780398198833312/image.png?ex=65b53c47&is=65a2c747&hm=81f31616aa5750b5539b7bef9ff3771c88968b92332f09eae5dffba84595cc1e&=&format=webp&quality=lossless&width=745&height=623


Batchfile thats Obfuscated: https://github.com/baris1337/growdice-fake-mines-predictor/blob/main/start.bat
And has been used for multiple repos.

**Comment by baris1337** [comment]
get a job lil nigga 😭

**Comment by EvilBytecode** [comment]
Currently In Touch with NCSC [National Cyber Security Centre], we will be contacting you shortly and github probably too.

**Comment by baris1337** [comment]
🤣🤣🤣

**Comment by EvilBytecode** [comment]
Keep Laughing
